### ISSUE TITLE
Версии курсов, уроков, тестов, испытаний.

### ISSUE THREAD

**Issue by geozhur** [Hexlet/proposals#10]
Ввести версии для курсов, тестов, испытаний.

Скажем изначально версия курса 1.0.0 .  При появлении новых упражнений 2.0.0 .  При исправлении орфографических ошибок версия 2.0.1 , при логических изменений старых упражнений, теории, тестов,  версия 2.1.1 .

Версионность ввести в каждом упражнении, тестах, теории. 

Когда заканчиваешь курс, то заканчиваешь его строго такой то версии. Например. Начал я делать курс версии 1.0.0, пока его делал изменилось одна теория и в другое время одно упражнение и текущая версия изменилась на 1.2.0 . В конце я вижу, что мне надо либо доделать либо переделать эту теорию и упражнения, чтоб закончить текущий курс 1.2.0 . Со временем курс может изменить версию стать 4.2.3 . Я это сразу вижу у себя в списке прошедших курсов и могу допроходить его до текущей версии.

С учетом того, что в курсы вносятся изменения и исправления, это было бы очень полезно и понятно. Более того в дальнейшем помогло бы избежать всяких непонятных названий, из за того что скажем курс устарел и его перенесли в архив.

**Comment by mokevnin** [comment]
К сожалению версионность это рукопашная работа, ее невозможно автоматизировать. Мы каждый день делаем десятки коммитов от правки запятых до полного переписывания. Отслеживать это дело не представляется возможным, мы бы тогда просто перестали обновлять контент из-за необходимости постоянно все версионировать. Что мы точно сделаем, это будем оповещать о новых штуках, типа добавленной практике или квизе. На это есть отдельный ишьюс.
