### ISSUE TITLE
[Bug] Пропущенные слова?

### ISSUE THREAD

**Issue by ZoolooS** [Hexlet/proposals#102]
https://ru.hexlet.io/courses/python-data-abstraction/lessons/ontology/theory_unit

Третий с конца абзац:
> В зависимости от языка программирования будет меняться способ представления сущностей в коде. Например, **в некоторых с** помощью абстрактных типов данных, интерфейсов или классов определяются типы, в других — структуры, а в третьих не предоставляют никаких вариантов, кроме словарей — ассоциативных массивов.

В некоторых чём? Сущностях, приложениях, проектах, кодовых базах, ...?

**Comment by sgmdlt** [comment]
Добрый день, спасибо за замечание, поправлю.

Вы можете отправлять сообщения об опечатках на самом сайте, выделив текст и нажав CTRL + Enter.
proposals лучше использовать для глобальных советов по улучшению платформы.
