### ISSUE TITLE
Добавление дополнительных абстрактных иллюстраций в теорию

### ISSUE THREAD

**Issue by mxclg** [Hexlet/proposals#119]
Привет!

Я (а значит кто-то ещё из студентов Hexlet) лучше усваиваю техническую информацию через абстрактные иллюстрации и вообще через иллюстрации. Например, я понимаю, что быстро и четко усвоил различия между функциями высшего порядка, потому что в теории для каждой функции были картинки которые показывали как они работают (прилагаю примеры). Теперь у меня в голове просто всплывают эти картинки и я понимаю, какую функцию мне нужно использовать. 

Так вот, картинок очень не хватает в других уроках, например про ООП, абстракции и так далее. Сегодня я лучше смог понять this и часть ООП из-за картинок в презентации на вебинаре и с видео какого-то блогера. Потом я начал перечитывать теорию на Hexlet и мне уже было намного (намного!) легче. Было бы круто увидеть в теории больше иллюстраций. Даже самые простые, как видно в примерах, очень помогут.

![image](https://github.com/Hexlet/ru-proposals/assets/149499467/9d228961-cc96-4f6c-ab9d-0444f0d69c69)
![image](https://github.com/Hexlet/ru-proposals/assets/149499467/d674b8db-7f62-4272-b7ee-bec3f36d6488)

**Comment by fey** [comment]
Вы можете делиться обратной связью в уроках, предлагать идеи к иллюстрациям. Мы стараемся делать картинки, но к сожалению, без вашей ОС не сможем этого сделать. 
Поэтому если в будущем увидите место, где подошла бы картинка - создавайте топик :+1:

**Comment by mxclg** [comment]
> Вы можете делиться обратной связью в уроках, предлагать идеи к иллюстрациям. 

Да, я понимаю, что могу. Просто куратор попросил написать это предложение сюда.

> Поэтому если в будущем увидите место, где подошла бы картинка - создавайте топик 👍

Окей, то есть мне просто нужно написать в обсуждении к уроку, что мне было бы лучше понять этот урок с картинкой?

**Comment by fey** [comment]
Да, можете например референс приложить ;)

**Comment by mxclg** [comment]
А потом и нарисовать! 👨‍🎨

**Comment by fey** [comment]
ну нарисовать у нас есть иллюстратор, но вы можете референс нарисовать сами. например https://excalidraw.com/ использовать.

**Comment by mxclg** [comment]
про "нарисовать" я иронизировал и это не понятно в комментариях, извини.
спасибо за ссылку -- хороший сервис. я буду рад написать в обсуждениях к тому или иному уроку, что было бы здорово добавить картинку (и добавить какие-то пояснения), НО я не смогу добавить референс, потому что картинка мне как раз и нужна чтобы понять материал. Если бы я знал референс (= метафору), то мне бы не нужна была картинка, чтобы понять теорию:)
