### ISSUE TITLE
Новое испытание JS "Массивы"

### ISSUE THREAD

**Issue by Kulakoff1988** [Hexlet/proposals#18]
```
const size = 6;
const battleShips = [
  0, 1, 0, 0, 0, 0,
  0, 1, 0, 1, 1, 1,
  0, 0, 0, 0, 0, 0,
  0, 1, 1, 1, 0, 1,
  0, 0, 0, 0, 0, 1,
  1, 1, 0, 1, 0, 1,
];
```

Перед вами популярная игра "Морской бой". `size` - это размер стороны поля. Поле представлено массивом нулей и единиц. Ноль - пустая ячейка, единица - часть корабля. Корабли располагаются на поле так, как написано в коде. Нужно посчитать количество кораблей на поле.

**Comment by Kulakoff1988** [comment]
```
const calcShips = battleField => {
  let ships = 0
  for (let i = 0; i < battleField.length; i++) {
    if (battleField[i] && !battleField[i + 1] && !battleField[i + size]) {
      ships++;
    }
  }
  return ships;
}

**Comment by zhabinka** [comment]
А что, хорошее испытание.

**Comment by zhabinka** [comment]
@ashikov, давай добавим

**Comment by ashikov** [comment]
Готово.

**Comment by ashikov** [comment]
@zhabinka Думаю можно закрывать issue.

**Comment by vertalet76crew** [comment]
> ```
> const calcShips = battleField => {
>   let ships = 0
>   for (let i = 0; i < battleField.length; i++) {
>     if (battleField[i] && !battleField[i + 1] && !battleField[i + size]) {
>       ships++;
>     }
>   }
>   return ships;
> }
> ```

не сработает если передать массив  const battleField = [
        1, 0, 0, 1,
        0, 0, 0, 1,
        1, 0, 0, 0,
        0, 0, 1, 1
      ];


`const markShip = (i, j, field, fieldSize) => {
	const tempI = i;
  const tempJ = j;
	while(field[i * fieldSize + tempJ] !== 0 && i < fieldSize) {
  	field[i * fieldSize + tempJ] = -1;
    i++;
  }
  
  while(field[tempI * fieldSize + j] !== 0 && j < fieldSize) {
  	field[tempI * fieldSize + j] = -1;
    j++;
  }
}


function countShips(field) {
	let fieldSize = Math.sqrt(field.length);
  let totalShips = 0;
  
  for(let i = 0; i < field.length; i++) {
  	for(let j = 0; j < fieldSize; j++) {
    	if (field[i * fieldSize + j] === 1) {
      	totalShips++;
        markShip(i, j, field, fieldSize);
      }
		}
  }
  
  console.log(field)
  
  return totalShips
}`

**Comment by ZeroSteep** [comment]
предыдущий вариант рабочий, но слишком громозкий и куча циклов, можно пройти в один проход... хотя не все варианты проверял.

```export function countShips(field) {
  let count = 0;
  const square = Math.sqrt(field.length);

  for (let index = 0; index < field.length; index++) {
    const nextHorizonItem = field[index + 1];
    const nextVerticalItem = field[index + square];
    const prevVerticalItem = field[index - square];

    if (field[index] === 1) {
      if (!nextHorizonItem && !nextVerticalItem) {
        count++;
      }

      if (nextHorizonItem && prevVerticalItem) {
        count++;
      }
    }
  }

  return count;
}
