### ISSUE TITLE
Мои испытания: показывать только испытания текущей профессий 

### ISSUE THREAD

**Issue by baur** [Hexlet/proposals#20]
[Мои испытания](https://ru.hexlet.io/my/challenges): показывать только испытания текущей профессий, а то там все подряд

**Comment by mokevnin** [comment]
Они привязаны к курсам, а не к профессии, поэтому такой вывод. Но мы сделаем фильтрацию, которая позволит что-то подобное делать. Это описано в отдельном ишьюсе.
