### ISSUE TITLE
Обсуждения разделить на теория / тесты / упражнение

### ISSUE THREAD

**Issue by baur** [Hexlet/proposals#21]
Было бы удобно если они были разделены

**Comment by Colonizator1** [comment]
А куда запихивать вопросы такого плана: подскажите в теории была такая информация, я ее понял так и эдак, пытаюсь сделать упражнение вот эдак, но получается совсем не то ? Как вариант, не делить их: а при добавлении обсуждения предоставить возможность выбрать метку/тег (теория, обсуждение). И если автор посчитает это уместным - он ее укажет, или нет.

**Comment by mokevnin** [comment]
Такая детализация не сработает, потому что люди будут сами путаться, там все связано. Но за идею спасибо, мы постоянно смотрим на то, чтобы сделать наши обсуждения более дружелюбными.
