### ISSUE TITLE
Возможность ставить лайки решениям в испытаниях

### ISSUE THREAD

**Issue by leksuss** [Hexlet/proposals#22]
### Базовая идея
Всегда после прохождения испытания смотрю решения других учеников, и иногда решения бывают очень элегантны, и хочется как-то отметить свое восхищение решением.

### Чего еще можно прикрутить
Добавленные лайки могут влиять на общий рейтинг ученика, повышая геймификацию процесса обучения. Можно прикрутить запоминание поставленных лайков для того, кто их поставил, чтобы можно было возвращаться к этим решениям и медитировать )

**Comment by pavel-else** [comment]
Было бы также крыто иметь возможность оставлять к ревью комментарии

**Comment by mokevnin** [comment]
Вы не поверите, но это было изначально, когда мы только запилили такую функцию. Жизнь показала, что этими фичами почти не пользовались и мы убрали их чтобы не тратить время на поддержку.
