### ISSUE TITLE
Вкладка Решение

### ISSUE THREAD

**Issue by mishchenkoandrey** [Hexlet/proposals#23]
Для удобства сравнивания своего решения с решением учителя на странице упражнения нужно добавить вкладку Решение в блок Linter, Readme, Terminal 1, Terminal 2. Сейчас решение учителя отображается только в модальном окне.

**Comment by mokevnin** [comment]
Основной способ просматривать решение учителя это ревью. Модальное окно подходит только для маленьких упражнений.
