### ISSUE TITLE
Возможность посмотреть решение учителя в "Испытаниях"

### ISSUE THREAD

**Issue by ghost** [Hexlet/proposals#24]
На данный момент такой возможности нет и если не получается решить задачу (а некоторые задачи в "Испытаниях" очень трудные), то хотелось бы иметь возможность посмотреть решение учителя (разумеется, с аннулированием баллов за упражнение) и разобраться с этим решением.
Такая возможность же есть в упражнениях к урокам.

**Comment by mokevnin** [comment]
Сделали такое специально. Задумка в том чтобы помогать в обсуждениях. Поэтому если трудно, просто задайте туда вопрос и мы наведем на ответ)
