### ISSUE TITLE
Добавить тёмную тему в теорию

### ISSUE THREAD

**Issue by andreev-aa** [Hexlet/proposals#26]
Когда чаще стал заниматься ночами, столкнулся с проблемой переключения зрения с белого фона хекслета на тёмную VS. Это касается раздела теории и обсуждений.
https://prnt.sc/siu39a
Раньше меня это не сильно задевало, т.к. были условия работать при свете, но семья, дети, в общем, теперь там где удобно сидеть ночью нормального света не включить. 
После теста нескольких расширений в хроме (не на всех сайтах они работают) оставил Dark Mode On Chrome
https://prnt.sc/siu2qv

Но думаю будет всем приятней иметь переключатель в интерфейсе, и получить более эстетичное оформление, чем от расширения.

**Comment by ismailovsn** [comment]
Предложение старое, но актуальное. Ночью сидишь и глаза режет :(

**Comment by mokevnin** [comment]
Угу, ждем когда бутстрап доделают, они активно двигаются в эту сторону. Как только заработает, мы сразу внедрим

**Comment by dmitrykholopov** [comment]
Люто плюсую, а пока предлагаю небольшой "костыль" кому очень нужно (по крайней мере в Safari работает, уже писал сегодня на стриме Кирилла):  включаете ночной режим в системе и дальше - режим чтения. 
Вот так это на Маке выглядит, например - [http://joxi.ru/krDX0J3HGknK5r](url)

**Comment by irades** [comment]
Поддерживаю)

**Comment by kerman501** [comment]
расширение Dark Reader в хроме

**Comment by super-gr0ver** [comment]
Пожалуйста добавьте темную тему

**Comment by kaziamov** [comment]
Похожие #78 и #83

**Comment by fey** [comment]
Готово. темная тема завезена.
