### ISSUE TITLE
В испытаниях добавить несколько задач по сложности: легкий, средний, сложный

### ISSUE THREAD

**Issue by szharas** [Hexlet/proposals#28]
После пройденного урока есть только одно испытание, иногда легкая, иногда средняя, иногда совсем сложная. Предлагаю на каждый урок добавлять как минимум три испытания разной сложности. Например в javarush на каждый урок бывает по 8-12 задач. Это очень помогает укрепить полученные знания практикой. Помогает именно поэтапное прохождение задач, от легкого к сложному.

**Comment by mokevnin** [comment]
Это довольно непростой вопрос. Дело в том, что поддержка в актуально состоянии курсов это очень сложно. Помнить обо всем что происходит в курсах и строить связанную цепочку в голове – офигенно затратно. Даже по одной практике + испытания достаточно чтобы взорвалась голова. Причем у нас ведь не только джава, это куча стеков, которые во многом делались одним человеком (более 70 курсов).

Чтобы управлять этой сложностью нужны ограничения и определенные направления развития. Одна практика на урок относится к таким важным ограничениям. Когда мы видим что практика сложная или ее мало, из этого делается ровно следующие выводы, нужно упрощать практику/разбивать уроки. Это позволяет держать систему плоской и простой. А вот вся сложность уходит на испытания (которые идут после курсов). 

Единственное в этом деле требуется помощь от учеников, фидбек, который становится катализатором изменений.
