### ISSUE TITLE
Добавить раздел RoadMap

### ISSUE THREAD

**Issue by holiqen** [Hexlet/proposals#29]
Раздел, в котором можно отслеживать прогресс развития проекта. Какие-то курсы, испытания, профессии планируются к добавлению, а также остальной функционал. Отличным примером может быть Trello EGS [https://trello.com/b/GXLc34hk/epic-games-store-roadmap](url)

**Comment by mokevnin** [comment]
Делаем это с помощью дайджестов и вебинаров. Остальные подходы не взлетели, всегда забывают обновлять.
