### ISSUE TITLE
Начисление баллов за проект.

### ISSUE THREAD

**Issue by geozhur** [Hexlet/proposals#3]
Проекты значимая часть на Hexlet. Думаю необходимо начислять баллы за проекты. Баллы  можно высчитывать по простой формуле. Первый проект, второй, третий - недельные, значит за каждый проект по 70 баллов, за четвертый проект 300, по 10 баллов за день. Можно еще поделить на задания, 70 / число заданий и начислять за каждый пункт прохождения проекта.

**Comment by AlfredSorrow** [comment]
Скорее не согласен. Рейтинг это игровая часть обучения, и дополнительные баллы за проект это как payToWin в играх (хотя и нужно что-то совершать за этот Pay). Вероятно, уменьшится желание набирать больше баллов, так как труднее будет выйти в "победители".

**Comment by geozhur** [comment]
> Скорее не согласен. Рейтинг это игровая часть обучения, и дополнительные баллы за проект это как payToWin в играх (хотя и нужно что-то совершать за этот Pay). Вероятно, уменьшится желание набирать больше баллов, так как труднее будет выйти в "победители".

1. Да и сейчас выиграть может тот, кто платит, потому что испытания туда входят, в рейтинг.
2. Баллы зачисляются за прохождение проекта, а не за оплату его. Тут нет преимуществ.
3. Человек прошедший кучу проектов имеет рейтинг хуже, чем человек  у которого вообще нет не испытаний, не проектов, это ненормально.

**Comment by AlfredSorrow** [comment]
1. Только без подписки смысла в обучении практически нет (основ недостаточно, это и понятно). Да и цены совсем разные.
2. "Хотя и нужно что-то совершать за этот Pay". Преимущество в возможности получения. К тому же теперь проекты без срока. Вот когда давалась неделя, хех.
3. Ну можно уменьшить баллы за теорию :) Тогда только практиканты будут впереди. Хотя не встречал, чтобы те кто сделал кучу проектов отставали от тех, кто не делал испытания.

**Comment by dropbox533** [comment]
Баллы за проекты должны начисляться.

**Comment by glagius** [comment]
Для ЧСВ, можно сделать ачивки. И показывать их возле ника или еще где. Тогда не будет PayToWin но и студенту приятно :)

**Comment by mokevnin** [comment]
Праздник к нам приходит) Проекты становятся частью обычной подписки, поэтому мы включаем начисление баллов.
