### ISSUE TITLE
Hotkey ctrl + [

### ISSUE THREAD

**Issue by enmalafeev** [Hexlet/proposals#31]
В практике были добавлены hotkeys. В том числе ctrl + [ как переключение по вкладками. Раньше эта комбинация использовалась, чтобы увеличивать\уменьшать отступы в блоке кода. 
Как по мне, этот hotkey ctrl + [ лучше было также оставить для сдвигания блоков кода. По вкладкам можно и мышкой клацнуть. А вот форматировать отступы ручками больно.

**Comment by mokevnin** [comment]
@frontstall

**Comment by enmalafeev** [comment]
Рома вернул эти хоткеи уже. Закрываю issue )
