### ISSUE TITLE
Во время загрузки упражнения автоматический открывать описание задачи.

### ISSUE THREAD

**Issue by Yur-ok** [Hexlet/proposals#35]
- **URL** 
На все страницы с упражнениями.

- **Описание**
Т.к. подготовка окружения иногда может занимать продолжительное время, то приходится в ручную открывать описание задачи.
На мой взгляд было бы удобно реализовать подобное поведение по дефолту.

  - Пока поднимается окружения для выполнения задания

  - Открыть модальное окно с описанием задания.

**Comment by fey** [comment]
Done
