### ISSUE TITLE
Убрать в блоге box-shadow при клике на страницу

### ISSUE THREAD

**Issue by kcelsi** [Hexlet/proposals#36]
**URL**: https://ru.hexlet.io/blog/categories/hexlet?page=3
**Описание**: box-shadow в данном месте перекрывает другие кнопки. 
![image](https://user-images.githubusercontent.com/33805170/101128536-768aba80-3632-11eb-96f9-93cee9ed6a34.png)

**Comment by amshkv** [comment]
Кажется проблема сохраняется до сих пор, но я не очень понимаю что нужно убрать? Состояние фокуса с кнопки? но это же наоборот хорошо и позволяет соориентироваться где ты находишься, особенно при взаимодействии с клавиатуры
ПыСы: скоро до всех браузеров доедет focus-within и для кликов такого повторяться не будет. Но тут мы завязаны на бутстрап, и пока там это не настроят, мы изменить не сможем

**Comment by fey** [comment]
Тут будет без изменений, тк дефолтное поведение. В принципе другим кнопкам это не мешает :thinking:
