### ISSUE TITLE
Блог/дневник. 

### ISSUE THREAD

**Issue by Fessan-zz** [Hexlet/proposals#4]
Я уже общался по этому поводу. Но думаю нужно вынести на общее обсуждение.

Итак. У нас есть раздел в котором ученики пишут статьи для учеников. Но это не работает. Из учеников , статьи читают единицы ( это видно по количеству лайков) . И по факту , написание статьи имеет смысл лишь для буста про акка и бонусов за " как хекслет помог мне устроится на работу". 

С этого месяца Дмитрий стал делать подборку популярных за месяц статей и кидать их в #general . Но тут та же история. Лишь не значительная часть учеников есть в слаке. 

Да же я сам, и то редко захожу. Во первых слишком много действий что бы попасть в блог, во вторых я просто не знаю что там что то появилось! 
Хекслет не слишком известен, хотя в нем много полезных статей. 

Я новичок. И не знаю как решить эту проблему. На ум приходит какой нить банальный блок со списком новый статей, который всегда будет висеть на самых посещаемых страницах 

Ну и я бы ещё ввел возможность подписки на авторов. Что бы оповещения приходили так же , как это сделано сейчас в обсуждениях

**Comment by mokevnin** [comment]
Кажется эту проблему более менее решили.

**Comment by mokevnin** [comment]
> Из учеников , статьи читают единицы ( это видно по количеству лайков)

Это кстати не так, лайки особо не ставят просто потому что это ни на что не влияет (да и не сильно заметно). По аналитике народу туда ходить тьма.

**Comment by mokevnin** [comment]
> На ум приходит какой нить банальный блок со списком новый статей, который всегда будет висеть на самых посещаемых страницах

На /my теперь есть такой блок
