### ISSUE TITLE
в курсе JAVA сделать конспекты лекций

### ISSUE THREAD

**Issue by NikGor** [Hexlet/proposals#43]
Видеоуроки ужасно плохо подходят для обучения. Сегодня я посмотрел лекцию Егора, завтра сел делать домашку и приходится заново проматывать по секундам все видео, чтобы найти где именно объяснялся какой-то алгоритм, или метод. 
Было бы хорошо под каждым видео иметь материал урока в текстовом виде, иначе к сожалению приходится параллельно проходить курс на других ресурсах, например JAVARUSH, где материал всегда доступен в текстовом виде. Была даже мысль уйти на JAVARUSH полностью из-за этого

**Comment by mokevnin** [comment]
Да спасибо, мы над этим сейчас во всю работаем. Если вы видите где-то, где прямо не хватает информации, сразу пишите кураторам, они передадут внутрь команды контента, которая быстрее включится в конкретный урок.

**Comment by NikGor** [comment]
да это прям везде. Например есть прекрасный курс по Github, к которому можно в любой момент вернуться, и JAVA Core, к которому не вернёшься уже никак. Не будешь же заново пересматривать все часовые лекции. В первых уроках JAVA Core ещё есть куски кода из видео, а дальше только команды загрузки домашнего задания под видео. Смотрю дальнейшие курсы - JAVA коллекции, ООП, веб-технологии, и т.д., и с трудом представляю как их буду осваивать без сторонних ресурсов. Деньги все-таки за курс отданы серьёзные, а по факту приходится тратить ещё на другие подписки. Не все могут в лайв режиме усваивать, понимать и запоминать материал только из видео.

**Comment by fey** [comment]
Ищщус закрываю, поскольку сейчас большая часть проблемных лекций переписаны. Осталось не так уж много и оно будет доведено до конца. Можете пересмотреть новые тексты уроков.
