### ISSUE TITLE
Починить кнопку - Отправить проект на проверку

### ISSUE THREAD

**Issue by mkolotovich** [Hexlet/proposals#44]
В данный момент чтобы отправить проект на проверку необходимо два раза нажать кнопку - Отправить проект на проверку. При первом нажатии на эту кнопку запускается автопроверка. Для того чтобы отправить проект на проверку необходимо повторно нажать на эту кнопку. Я предлагаю либо сделать чтобы автопроверка и отправка проекта на проверку происходила при одном нажатии на эту кнопку либо в проектах указать, что эту кнопку необходимо нажимать дважды.

P.S. Такая ситуация была и у меня и у моего студента.

**Comment by fey** [comment]
Поправили. Сейчас тексты на кнопке разные и отправка выполняется без повтора.
