### ISSUE TITLE
Больше упражнений с возрастающей сложностью )

### ISSUE THREAD

**Issue by VaFed** [Hexlet/proposals#54]
Я вот с рекурсией и циклами туплю сильно. Может быть сделать курс чисто на упражнения ((( чтобы там была возрастающая сложность, и разные случаи, а то в существующих курсах бывает то сразу скачкообразно возрастает сложность то не успеваешь закрепить ввиду недостаточного количества упражнений. Спасибо )

**Comment by fey** [comment]
Добрый день.

А какой у вас стек (язык)?
А вы проходили треки по SICP?
https://ru.hexlet.io/programs/js-sicp
Также добавлю - проходили вы испытания? И в каком курсе столкнулись со скачкообразной сложностью?
Можете скинуть ссылку на свой профиль =)

**Comment by VaFed** [comment]
Благодарю. Только сейчас увидел Ваше письмо. Полезный курс.

пн, 18 июл. 2022 г. в 14:32, Nikolay Gagarinov ***@***.***>:
