### ISSUE TITLE
Сделать что-то с постоянно всплывающим из сердечка окошком "Как вам у нас?" слева внизу

### ISSUE THREAD

**Issue by dmitrykholopov** [Hexlet/proposals#56]
Очень надоело и очень отвлекает, или сделайте чек-бокс "не напоминать больше" или поставьте тайм-аут в неделю, ну не хочу я именно сейчас никаких отзывов оставлять, зачем оно мне?
[http://joxi.ru/Grq49ZEUzjMQ9A](url)
Второе окошко - то же самое, достает, причем как раз анкету я, вроде, как сразу заполнил...
Я понимаю, что статистика и отзывы - это хорошо, но надо же как-то и интересы пользователя соблюдать? ИМХО, слишком навязчиво.

Браузер - Safari (iMac, iPhone).

**Comment by ashikov** [comment]
@amshkv точно не знаю кого тегать, поэтому "тыц". Возможно криминал.

**Comment by amshkv** [comment]
это к ребятам из маркетинга, спасибо, передал
ПыСы: у вас ссылка не совсем верно вставлена ;)

**Comment by dmitrykholopov** [comment]
[ссылка](http://joxi.ru/Grq49ZEUzjMQ9A)

**Comment by amshkv** [comment]
Докладываю. Это был баг именно с этим сообщением, выключили сайтмесседжи, сейчас все должно быть хорошо
