### ISSUE TITLE
Два раза вопрос про наставника в разделе "Вопросы и ответы" на страничке QA инженеров

### ISSUE THREAD

**Issue by bazilval** [Hexlet/proposals#64]
[Ссылка на страничку](https://ru.hexlet.io/programs/qa-engineer)

![image](https://user-images.githubusercontent.com/29205112/194563439-f3cb81d4-8871-4b1a-ac77-fe766a1bdc89.png)

P.S.: это можно считать тестовым заданием для скидки на обучение тестированию? :)

**Comment by amshkv** [comment]
Поправили, большое спасибо!)
Скидку дать не могу, а заметить что вы наблюдательный и это пригодится в вашей будущей профессии — могу!
Спасибо
