### ISSUE TITLE
Ошибка 404. Курс "Основы JavaScript", тема "Переменные" ссылка на реальный код Хекслета. 

### ISSUE THREAD

**Issue by DariaKobeleva** [Hexlet/proposals#66]
<img width="1440" alt="Снимок экрана 2022-10-12 в 12 29 24" src="https://user-images.githubusercontent.com/105724919/195319960-fc608d99-0245-4909-85b1-56a111741f0b.png">

<img width="795" alt="Снимок экрана 2022-10-12 в 12 27 36" src="https://user-images.githubusercontent.com/105724919/195320000-57daf899-d7ca-4d92-9ac5-25f309bf196b.png">

**Comment by DariaKobeleva** [comment]
https://ru.hexlet.io/courses/js-basics/lessons/variables/theory_unit

**Comment by fey** [comment]
Ссылка теперь рабочая.
