### ISSUE TITLE
У вас вход на сайте не работает, кнопка не нажимается.

### ISSUE THREAD

**Issue by buriy** [Hexlet/proposals#74]

**Comment by amshkv** [comment]
Привет
Подскажи пожалуйста, какая кнопка не нажимается? можешь прислать скрин пожалуйста?
и подсказать на каком устройстве/браузере не работает?

**Comment by buriy** [comment]
Кнопки Вход и регистрация. Сверху кнопки пару пикселей реагирует и оно focused становится, а на всё остальное место не реагирует. Вчера вообще не реагировало, наверное, ширина-высота окна браузера у меня была другая. Yandex browser for Linuх 22.7.5.1936 beta
А всё потому, что у вас там невидимый credential_picker_container с z-index 9999 стоит.
![telegram-cloud-photo-size-2-5409215962047168681-x](https://user-images.githubusercontent.com/21124/199501390-4ca836fd-7af7-48f5-9a47-92fade499c11.jpg)

**Comment by amshkv** [comment]
а можешь еще посмотреть пожалуйста консоль разработчика, скорее всего не включился скрипт входа через гугл

**Comment by amshkv** [comment]
починили, проверяй :)
