### ISSUE TITLE
Лента изменение проекта hexlet.

### ISSUE THREAD

**Issue by geozhur** [Hexlet/proposals#8]
Отдельный блог, в котором выписываются изменения проект hexlet. Например, когда появляются новые упражнения или удаляются, или какие-то изменения правки. Информация полезна и нужна, очень сложно отслеживать ее сейчас.

**Comment by mokevnin** [comment]
Делаем это с помощью ежемесячного дайджеста. Что касается уведомления о новых шагах в курсе, это сделаем. Есть отдельный ишьюс под задачу.
