### ISSUE TITLE
Темная тема для хекслета

### ISSUE THREAD

**Issue by Piro94** [Hexlet/proposals#83]
Возможность включать/выключать темную тему на сайте, кнопка переключения

**Comment by kaziamov** [comment]
Мне кажется можно объединить с #78

**Comment by artemBeletzky** [comment]
Всем привет! Есть ли какие-то новости по этой фиче? Bootstrap вроде как с версии 5.3.0 поддерживает уже темную тему.

**Comment by fey** [comment]
Привет. Да, ребята щас этим заняты. Не могу сказать, когда окончательно сделаю.
![image](https://user-images.githubusercontent.com/697178/233652219-3ce6b213-f71d-41cf-a708-38d8c6557249.png)

**Comment by fey** [comment]
Готово. Темная тема завезена.
