### ISSUE TITLE
Обновить действие `actions/checkout@v2` для использования с Node.js 16

### ISSUE THREAD

**Issue by NiyazGaripov** [Hexlet/proposals#88]
### URL/место исправления
Файл `hexlet-check.yml` в создаваемых репозиториях для проектов

### Описание
При сборке проекта прогоняются автоматические тесты. При их завершении возникает предупреждение 

```
Annotations
1 warning
build
Node.js 12 actions are deprecated.
Please update the following actions to use Node.js 16: actions/checkout@v2. 
For more information see: 
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```
Это происходит из-за того, что Node.js 12 находится в статусе **deprecated**. 
[Статья с переездом на Node.js 16](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)

### Скриншоты

<img width="1157" alt="Screenshot 2023-01-23 at 19 11 05" src="https://user-images.githubusercontent.com/24496044/214089985-23529ab3-8d57-4089-953f-d2fb58d35a3b.png">
<img width="816" alt="Screenshot 2023-01-23 at 19 11 20" src="https://user-images.githubusercontent.com/24496044/214090000-cdee606b-7d00-4906-a1e9-5440d761d720.png">

**Comment by amshkv** [comment]
взяли в беклог задач, спасибо! ❤️

**Comment by fey** [comment]
@NiyazGaripov эту штуку поправили. можете попробовать на каком-то из проектов (новом или старом) заново сделать подготовку репозитория.
