### ISSUE TITLE
Просмотр курсов, которых нет в списке. 

### ISSUE THREAD

**Issue by SadLaboka** [Hexlet/proposals#89]
Сейчас в списке курсов по языку GO есть только бесплатный базовый курс. Но если нажать на трек "Веб разработка на GO", то можно зайти в другие курсы. Выглядит так, как-будто так быть не должно. 

![first](https://sun9-80.userapi.com/impg/lH40uQQqO-iKiLHFXYwvWc4Y41fH7z3F0H2O7g/p9HLIPCNxHo.jpg?size=637x213&quality=95&sign=fea1d31381277410d96a9412a15f820b&type=album)

![second](https://sun9-81.userapi.com/impg/PKKyCHCnIo1OSPGdh69y2CqcHBpNzSpmuV76eQ/pV3SlB7jMJQ.jpg?size=847x295&quality=95&sign=dafc54d0950c5a145368ce392429781c&type=album)

![third](https://sun9-61.userapi.com/impg/5Whl3Ud5l_wcyjHPcD_L_Yz7LUdg3uGXEXmr1A/DZ2fGqZThmc.jpg?size=1392x885&quality=95&sign=6f0d0247cdb5cfc3371a2603f03c87c2&type=album)

**Comment by emp7yhead** [comment]
Спасибо, что обратили на это внимание. Добавил недостающие курсы в список курсов.
