### ISSUE TITLE
При смене языка обнуляются очки и рейтинг пользователя

### ISSUE THREAD

**Issue by AllIzm** [Hexlet/proposals#93]
**Summary**
При переключении языка с русского на английский в личном кабинете пользователя обнуляются очки и рейтинг.

**Browsers**
1. Google Chrome 110.0.5481.178 (Официальная сборка) (64 бит) 
2. Safari

**OS**
1. ОС Windows 11 22H2
2. iOS16.2

Reproduction steps
1. Открыть личный кабинет зарегистрированного пользователя с ненулевым количеством очков.
2. В футере в выпадающем меню "Язык" выбрать английский язык.

**Expected result**
При смене языка очки и рейтинг остаются неизменными.

Actual result
При смене языка очки и рейтинг обнуляются.

Язык=Русский
![Снимок2](https://user-images.githubusercontent.com/121917310/225145032-685fd0c5-a41c-4eca-a403-71ec102afca1.png)

Language=English
![Снимок1](https://user-images.githubusercontent.com/121917310/225145064-b6556e52-7b31-4ca0-9f06-202367bde37a.png)

**Comment by AllIzm** [comment]
Дополню, что:
- содержание страницы при переключении языка меняется (см скрин выше);
- доступ к пройденным курсам пропадает.
![image](https://user-images.githubusercontent.com/121917310/225147356-9415e308-6b97-4848-a7f6-7902ff8ec166.png)

**Comment by amshkv** [comment]
Привет :)
С точки зрения системы - русскоязычная и англоязычная платформы - это разные сайты со своими наборами курсов, программ, рейтингом, стоимостью подписок и всем таким
и их объединяет только пользователь, который может быть мультиязычным и проходить курсы из разных локалей :)
Так что это не баг, а фича, а скорее особенность
но большое спасибо за то что заметили и обратили внимание :)
