### ISSUE TITLE
Во втором шаге второго проекта QA нужно изменить Slack на Mattermost

### ISSUE THREAD

**Issue by AGrigorchenkoAI** [Hexlet/proposals#94]
<img width="818" alt="Снимок экрана 2023-03-17 в 12 32 05" src="https://user-images.githubusercontent.com/99707629/225866842-79d21176-0cce-499a-b080-6b78bc998d7c.png">

Второй шаг второго проекта программы Инженер по тестированию
В ссылках и задачах  нужно поменять канал в Slack на Mattermost.

**Comment by ssssank** [comment]
Исправили
