### ISSUE TITLE
Встроенные анимации консоли теперь открываются только в новом окне (asciinema.org).

### ISSUE THREAD

**Issue by ZoolooS** [Hexlet/proposals#98]
По сути FYK, а не issue.

В уроках время от времени авторы используют ролики показывающие какую-то работу в консоли. Раньше такие ролики проигрывались прямо в странице с уроком, теперь же висит только стопкадр, а клик на него открывает новую вкладку браузера откуда (https://asciinema.org) собственно ролик и шарился.
Например, столкнулся с этим при прохождении https://ru.hexlet.io/courses/python-setup-environment/lessons/getting-pip/theory_unit

Возможно так и было задумано при переписывании уроков, а возможно asciinema.org изменили что-то в своих политиках или API по встраиванию роликов на сторонних ресурсах и интеграция отвалилась.

**Comment by ashikov** [comment]
Спасибо, что обратили внимание! Тут дело в том, каким образом аскинема добавлена в урок. Я проверю, чтобы везде в курсах она открывалась на текущей странице в плеере.

**Comment by fey** [comment]
Кажется поправили.
